import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Privacy Policy",
	description: "Privacy policy for FireDash.",
};

type PrivacySubsection = {
	title: string;
	paragraphs?: string[];
	bullets?: string[];
};

type PrivacySection = {
	title: string;
	paragraphs?: string[];
	bullets?: string[];
	subsections?: PrivacySubsection[];
};

const sections: PrivacySection[] = [
	{
		title: "1. Introduction",
		paragraphs: [
			'FireDash ("we", "us", "our") values your privacy. This Privacy Policy explains how we collect, use, and protect data when you use our incident management software (the "Service").',
			"By using the Service, you agree to this Privacy Policy.",
		],
	},
	{
		title: "2. Data We Collect",
		subsections: [
			{
				title: "2.1 Customer Data",
				paragraphs: [
					"Incident records, logs, and operational data uploaded or generated by your organization.",
					"This data remains your property.",
					"We do not access or use this data except to provide the Service.",
				],
			},
			{
				title: "2.2 Personal Data",
				paragraphs: ["The only personal data we may process is:"],
				bullets: ["Name (from SSO or account creation)", "Email (if provided via SSO or for account notifications)"],
			},
			{
				title: "",
				paragraphs: ["We do not collect sensitive personal data unless you provide it as part of incident records."],
			},
		],
	},
	{
		title: "3. How We Use Data",
		bullets: ["To provide, maintain, and improve the Service", "To create and manage accounts", "To communicate with you about the Service (notifications, updates, billing)"],
		paragraphs: ["We do not sell, rent, or trade your data."],
	},
	{
		title: "4. Legal Basis for Processing",
		paragraphs: ["Under GDPR, our legal basis is:"],
		bullets: [
			"Performance of contract: We process Customer Data to deliver the Service you subscribed to",
			"Legitimate interest: We process minimal personal data to manage accounts and Service operations",
		],
	},
	{
		title: "5. Data Sharing",
		paragraphs: ["We do not share Customer Data with third parties, except:"],
		bullets: [
			"With service providers (e.g., Stripe for payments, Vercel for hosting) under strict confidentiality agreements and GDPR-compliant contracts",
			"If required by law or legal process",
		],
		subsections: [
			{
				title: "",
				paragraphs: ["Personal data is only shared when necessary for account management or technical support."],
			},
		],
	},
	{
		title: "6. Data Security",
		paragraphs: ["We implement reasonable technical and organizational measures to protect data from unauthorized access, alteration, or loss.", "Measures include:"],
		bullets: ["Encrypted storage of sensitive data", "Restricted access to employees or contractors with a legitimate need", "Regular security monitoring and updates"],
	},
	{
		title: "7. Data Retention",
		paragraphs: [
			"Customer Data is retained as long as your account is active.",
			"Personal data from SSO/account creation is retained for as long as necessary to provide the Service and comply with legal obligations.",
			"When you delete your account or cancel your subscription, Customer Data is deleted upon request.",
		],
	},
	{
		title: "8. Your Rights",
		paragraphs: ["Under GDPR, you have the right to:"],
		bullets: [
			"Access your personal data",
			"Request correction or deletion",
			"Object to or restrict processing",
			"Data portability (where applicable)",
			"Withdraw consent (where processing is consent-based)",
		],
		subsections: [
			{
				title: "",
				paragraphs: ["To exercise these rights, contact us at hello@firedash.ai."],
			},
		],
	},
	{
		title: "9. Cookies and Tracking",
		paragraphs: ["We may use minimal cookies or analytics tools to maintain sessions and improve the Service. No marketing cookies are used."],
	},
	{
		title: "10. Third-Party Services",
		paragraphs: ["We rely on third-party providers (e.g., Stripe, Vercel) to operate the Service.", "These providers are bound by confidentiality and GDPR-compliant agreements."],
	},
	{
		title: "11. International Data Transfers",
		paragraphs: [
			"Some third-party service providers we use (e.g., Vercel, Stripe) may process data outside the European Economic Area (EEA).",
			"When we transfer data internationally, we ensure appropriate safeguards to protect your rights and comply with GDPR, including:",
		],
		bullets: ["Standard Contractual Clauses approved by the European Commission", "Ensuring that the third-party provides a level of data protection equivalent to EU standards"],
		subsections: [
			{
				title: "",
				paragraphs: ["By using our Service, you consent to such international transfers for the purposes of providing, maintaining, and supporting the Service."],
			},
		],
	},
	{
		title: "12. Updates to This Policy",
		paragraphs: [
			"We may update this Privacy Policy periodically.",
			"We will notify you of major changes, and continued use of the Service constitutes acceptance of the updated policy.",
		],
	},
	{
		title: "13. Contact Us",
		paragraphs: ["For questions about this Privacy Policy or data processing, contact:"],
		bullets: ["FireDash", "Email: hello@firedash.ai"],
	},
];

export default function PrivacyPage() {
	return (
		<div className="mx-auto w-full max-w-4xl px-6 pb-24 pt-12 md:pt-16">
			<section className="rounded-[30px] border border-[#dbe3ed] bg-[#ffffff] p-8 md:p-10">
				<p className="font-mono text-xs uppercase tracking-[0.2em] text-[#64748b]">FireDash</p>
				<h1 className="mt-3 text-4xl leading-tight font-semibold tracking-tight text-[#0f172a] md:text-5xl">Privacy Policy</h1>
				<p className="mt-3 text-sm text-[#64748b]">Last updated: February 27, 2026</p>

				<div className="mt-8 space-y-7">
					{sections.map((section) => (
						<article key={section.title}>
							<h2 className="text-xl font-semibold tracking-tight text-[#0f172a]">{section.title}</h2>
							{section.paragraphs?.map((paragraph) => (
								<p key={paragraph} className="mt-2 text-sm leading-relaxed text-[#64748b]">
									{paragraph}
								</p>
							))}
							{section.bullets && section.bullets.length > 0 ? (
								<ul className="mt-2 list-disc space-y-1 pl-6 text-sm leading-relaxed text-[#64748b]">
									{section.bullets.map((bullet) => (
										<li key={bullet}>{bullet}</li>
									))}
								</ul>
							) : null}
							{section.subsections?.map((subsection, index) => (
								<div key={`${section.title}-subsection-${index}`} className="mt-4">
									{subsection.title ? <h3 className="text-sm font-semibold tracking-tight text-[#0f172a]">{subsection.title}</h3> : null}
									{subsection.paragraphs?.map((paragraph) => (
										<p key={paragraph} className="mt-2 text-sm leading-relaxed text-[#64748b]">
											{paragraph}
										</p>
									))}
									{subsection.bullets && subsection.bullets.length > 0 ? (
										<ul className="mt-2 list-disc space-y-1 pl-6 text-sm leading-relaxed text-[#64748b]">
											{subsection.bullets.map((bullet) => (
												<li key={bullet}>{bullet}</li>
											))}
										</ul>
									) : null}
								</div>
							))}
						</article>
					))}
				</div>
			</section>
		</div>
	);
}
